<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['openldap_directory_accounts_access'] = 'Accounts Access';
$lang['openldap_directory_accounts_access_invalid'] = 'Accounts access is invalid.';
$lang['openldap_directory_accounts_dn'] = 'Accounts DN';
$lang['openldap_directory_anonymous'] = 'Anonymous';
$lang['openldap_directory_app_description'] = 'The Directory Server provides information on users, groups and systems.  You can provide read only access to your directory to integrate third party applications both locally and in the cloud.';
$lang['openldap_directory_app_name'] = 'Directory Server';
$lang['openldap_directory_initialize_help'] = 'When initializing your Directory Server, please select the base domain that you use for your organization.  This domain is used for authentication and other system services.';
$lang['openldap_directory_openldap_directory_driver'] = 'OpenLDAP Directory Driver';
$lang['openldap_directory_openldap_directory_driver_description'] = 'The OpenLDAP driver for directory services';
$lang['openldap_directory_password_access'] = 'Password Access';
$lang['openldap_directory_policies'] = 'Policies';
