#!/bin/sh

# Restart webconfig due to LDAP library
#--------------------------------------

/usr/sbin/webconfig-restart

# Reload clearsyncd
#------------------

/sbin/service clearsyncd condrestart >/dev/null 2>&1

