#!/bin/sh

# Sudoers entry
#--------------

/usr/sbin/addsudo /usr/sbin/authconfig app-openldap-directory-core
/usr/sbin/addsudo /usr/sbin/slapcat app-openldap-directory-core
/usr/sbin/addsudo /usr/sbin/app-openldap-directory-initialize app-openldap-directory-core
