<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['openldap_directory_alias_with_this_name_exists'] = 'Alias bereits vorhanden.';
$lang['openldap_directory_app_description'] = 'Der Verzeichnisserver stellt Informationen zu Benutzern, Gruppen und Systemen bereit.  Wenn Sie lokale oder Cloudbasierte Drittanbietersoftware integrieren möchten, besteht die Möglichkeit den Zugriff nur lesend auf das Verzeichnis zu gewähren.';
$lang['openldap_directory_app_name'] = 'Verzeichnis Server';
$lang['openldap_directory_base_dn'] = 'Base DN';
$lang['openldap_directory_base_domain'] = 'Base Domäne';
$lang['openldap_directory_bind_dn'] = 'Bind DN';
$lang['openldap_directory_bind_password'] = 'Bind Passwort';
$lang['openldap_directory_capabilities'] = 'Fähigkeiten';
$lang['openldap_directory_computers'] = 'Computer';
$lang['openldap_directory_connection_information'] = 'Verbindungsinformationen';
$lang['openldap_directory_containers'] = 'Container';
$lang['openldap_directory_directory_information'] = 'Verzeichnisinformationen';
$lang['openldap_directory_directory_status'] = 'Verzeichnisstatus';
$lang['openldap_directory_group_with_this_name_exists'] = 'Gruppenname bereits vorhanden.';
$lang['openldap_directory_importing_data'] = 'Daten importieren.';
$lang['openldap_directory_initialize_help'] = 'Um Ihren Directory Server zu initialisieren wählen Sie bitte die Default Domäne die Sie für Ihre Firma verwenden.  Diese Domäne wird für Anmeldeauthentifizierung und andere Systemdienste verwendet.';
$lang['openldap_directory_mode'] = 'Modus';
$lang['openldap_directory_openldap_directory_driver'] = 'OpenLDAP Verzeichnistreiber';
$lang['openldap_directory_openldap_directory_driver_description'] = 'Der Treiber für OpenLDAP Verzeichnisdienste';
$lang['openldap_directory_preparing_import'] = 'Import wird vorbereitet.';
$lang['openldap_directory_publish_policy'] = 'Richtlinie veröffentlichen';
$lang['openldap_directory_reserved_for_system_use'] = 'Für Systemnutzung reserviert.';
$lang['openldap_directory_shutting_down_ldap_server'] = 'LDAP Server wird heruntergefahren.';
$lang['openldap_directory_username_with_this_name_exists'] = 'Benutzername bereits vorhanden.';
