<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['openldap_directory_accounts_access'] = 'Accounts Access';
$lang['openldap_directory_accounts_access_invalid'] = 'Accounts access is invalid.';
$lang['openldap_directory_accounts_dn'] = 'Accounts DN';
$lang['openldap_directory_anonymous'] = 'Anonymous';
$lang['openldap_directory_app_description'] = 'Der Verzeichnisserver stellt Informationen zu Benutzern, Gruppen und Systemen bereit.  Wenn Sie lokale oder Cloudbasierte Drittanbietersoftware integrieren möchten, besteht die Möglichkeit den Zugriff nur lesend auf das Verzeichnis zu gewähren.';
$lang['openldap_directory_app_name'] = 'Verzeichnis Server';
$lang['openldap_directory_initialize_help'] = 'Um Ihren Directory Server zu initialisieren wählen Sie bitte die Default Domäne die Sie für Ihre Firma verwenden.  Diese Domäne wird für Anmeldeauthentifizierung und andere Systemdienste verwendet.';
$lang['openldap_directory_openldap_directory_driver'] = 'OpenLDAP Verzeichnistreiber';
$lang['openldap_directory_openldap_directory_driver_description'] = 'Der Treiber für OpenLDAP Verzeichnisdienste';
$lang['openldap_directory_password_access'] = 'Password Access';
$lang['openldap_directory_policies'] = 'Policies';
