<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['openldap_directory_app_description'] = 'Der Verzeichnisserver stellt Informationen zu Benutzern, Gruppen und Systemen bereit.  Wenn Sie lokale oder Cloudbasierte Drittanbietersoftware integrieren möchten, besteht die Möglichkeit den Zugriff nur lesend auf das Verzeichnis zu gewähren.';
$lang['openldap_directory_app_name'] = 'Verzeichnis Server';
$lang['openldap_directory_initialize_help'] = 'Um Ihren Directory Server zu initialisieren wählen Sie bitte die Default Domäne die Sie für Ihre Firma verwenden.  Diese Domäne wird für Anmeldeauthentifizierung und andere Systemdienste verwendet.';
$lang['openldap_directory_openldap_directory_driver'] = 'OpenLDAP Verzeichnistreiber';
$lang['openldap_directory_openldap_directory_driver_description'] = 'Der Treiber für OpenLDAP Verzeichnisdienste';
