<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['openldap_directory_alias_with_this_name_exists'] = 'Alias med detta namn existerar redan.';
$lang['openldap_directory_app_description'] = 'Katalogservern ger information om användare, grupper och system.  Du kan dela ut endast läsrättigheter till dina mappar för att integrera tredjeparts-applicationer både lokalt och i molnet.';
$lang['openldap_directory_app_name'] = 'Katalogserver';
$lang['openldap_directory_base_dn'] = 'Base DN';
$lang['openldap_directory_base_domain'] = 'Basdomän';
$lang['openldap_directory_bind_dn'] = 'Bind DN';
$lang['openldap_directory_bind_password'] = 'Bind lösenord';
$lang['openldap_directory_capabilities'] = 'Förmågor';
$lang['openldap_directory_computers'] = 'Datorer';
$lang['openldap_directory_connection_information'] = 'Anslutningsinformation';
$lang['openldap_directory_containers'] = 'Behållare';
$lang['openldap_directory_directory_information'] = 'Kataloginformation';
$lang['openldap_directory_directory_status'] = 'Katalogstatus';
$lang['openldap_directory_group_with_this_name_exists'] = 'Grupp med detta namn existerar redan.';
$lang['openldap_directory_importing_data'] = 'Importera data.';
$lang['openldap_directory_initialize_help'] = 'Vid initieringen av den katalogserver, välj den basdomän som du använder för din organisation.  Denna domän används för autenticiering och andra systemtjänster.';
$lang['openldap_directory_mode'] = 'Mod';
$lang['openldap_directory_openldap_directory_driver'] = 'OpenLDAP katalogdrivrutinen';
$lang['openldap_directory_openldap_directory_driver_description'] = 'OpenLDAP drivrutinen för katalogtjänsten';
$lang['openldap_directory_preparing_import'] = 'Förbereder import.';
$lang['openldap_directory_publish_policy'] = 'Publiseringspolicy';
$lang['openldap_directory_reserved_for_system_use'] = 'Reserverad för systemet.';
$lang['openldap_directory_shutting_down_ldap_server'] = 'Stoppar LDAP-servern.';
$lang['openldap_directory_username_with_this_name_exists'] = 'Användare med detta namn existerar redan.';
