<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['openldap_directory_app_description'] = 'Katalogservern ger information om användare, grupper och system.  Du kan dela ut endast läsrättigheter till dina mappar för att integrera tredjeparts-applicationer både lokalt och i molnet.';
$lang['openldap_directory_app_name'] = 'Katalogserver';
$lang['openldap_directory_initialize_help'] = 'Vid initieringen av den katalogserver, välj den basdomän som du använder för din organisation.  Denna domän används för autenticiering och andra systemtjänster.';
$lang['openldap_directory_openldap_directory_driver'] = 'OpenLDAP katalogdrivrutinen';
$lang['openldap_directory_openldap_directory_driver_description'] = 'OpenLDAP drivrutinen för katalogtjänsten';
