<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['openldap_directory_accounts_access'] = 'Dostęp kont';
$lang['openldap_directory_accounts_access_invalid'] = 'Dostęp konta jest nieprawidłowy.';
$lang['openldap_directory_accounts_dn'] = 'DN konta';
$lang['openldap_directory_anonymous'] = 'Anonimowy';
$lang['openldap_directory_app_description'] = 'Serwer katalogowy dostarcza informacji o użytkownikach, grupach i systemie.  Możesz umożliwić dostęp tylko do odczytu do usługi katalogowej aby zintegrować aplikacje innych producentów zarówno lokalnie jak i w chmurze.';
$lang['openldap_directory_app_name'] = 'Serwer katalogowy';
$lang['openldap_directory_initialize_help'] = 'Podczas inicjowania Twojego serwera katalogowego proszę podać domenę podstawową, której używa Twoja organizacja.  Domena ta jest używana do autoryzacji oraz do innych usług systemowych.';
$lang['openldap_directory_openldap_directory_driver'] = 'Silnik katalogowy OpenLDAP';
$lang['openldap_directory_openldap_directory_driver_description'] = 'Silnik OpenLDAP dla usług katalogowych';
$lang['openldap_directory_password_access'] = 'Dostęp na hasło';
$lang['openldap_directory_policies'] = 'Reguły';
